/**
 * Formats a bill/invoice as a clean, modern, and professional WhatsApp receipt.
 * Suitable for retail/POS businesses with vertical alignment, clear hierarchy, and spare emojis.
 */
export const formatWhatsAppReceipt = (bill, settings = {}, business = {}, pdfUrl = '') => {
  if (!bill) return ''

  // Emojis for metadata (sparingly, clean)
  // Determine Payment Status Icon
  let statusIcon = '❌'
  let statusLabel = 'UNPAID'
  
  const balance = Number(bill.balance ?? 0)
  const amountPaid = Number(bill.amountPaid ?? 0)
  const total = Number(bill.total ?? 0)

  if (balance <= 0 || amountPaid >= total) {
    statusIcon = '✅'
    statusLabel = 'PAID'
  } else if (amountPaid > 0) {
    statusIcon = '🟨'
    statusLabel = 'PARTIAL'
  }

  const divider = '━━━━━━━━━━━━━━━━━━━━━━━'
  const monoDivider = '───────────────────────' // 23 chars for narrow mobile screen compatibility
  const totalDivider = '======================='
  
  // Mono pad helper
  const padLine = (left, right, width = 23) => {
    const padLength = width - left.length - right.length
    return left + ' '.repeat(Math.max(1, padLength)) + right
  }

  const header = `🧾 *${(business?.shopName || 'PRINTPRO').toUpperCase()} RECEIPT*`
  
  // Metadata Section
  const invoiceLine = `📄 *Invoice:* ${bill.id}`
  const dateLine = `📅 *Date:* ${bill.date}`
  const customerLine = `👤 *Customer:* ${bill.customerName || 'Guest'}`
  const statusLine = `💳 *Payment Status:* ${statusIcon} ${statusLabel}`

  const metadataSection = [
    invoiceLine,
    dateLine,
    customerLine,
    statusLine
  ].join('\n')

  // Mono section construction
  const monoLines = []
  
  // Check if itemized
  const hasItems = bill.items && bill.items.length > 0
  if (hasItems) {
    monoLines.push('📦 ITEMS\n')
    bill.items.forEach((item, index) => {
      const maxNameLen = 11
      let name = item.itemName || item.name || 'Item'
      if (name.length > maxNameLen) {
        name = name.substring(0, maxNameLen - 3) + '...'
      }
      const qtyStr = ` x${item.qty}`
      const leftSide = `${index + 1}. ${name}${qtyStr}`
      const rightSide = `₹${Number(item.amount || 0).toFixed(2)}`
      monoLines.push(padLine(leftSide, rightSide))
    })
    monoLines.push(monoDivider)
  }

  // Summary Lines
  const subtotalStr = `₹${Number(bill.subtotal || 0).toFixed(2)}`
  monoLines.push(padLine('Subtotal', subtotalStr))

  // Discounts (could be normal discount, promo discount, or loyalty discount)
  const totalDiscount = (Number(bill.discountAmount || 0) + Number(bill.promoDiscount || 0) + Number(bill.loyaltyDiscount || 0))
  if (totalDiscount > 0) {
    const discountStr = `-₹${totalDiscount.toFixed(2)}`
    monoLines.push(padLine('Discount', discountStr))
  }

  // GST
  const gstAmount = Number(bill.gstAmount || 0)
  if (gstAmount > 0) {
    if (settings.showGstBreakdown !== false) {
      const halfGst = (gstAmount / 2).toFixed(2)
      monoLines.push(padLine('CGST', `₹${halfGst}`))
      monoLines.push(padLine('SGST', `₹${halfGst}`))
    } else {
      monoLines.push(padLine('GST', `₹${gstAmount.toFixed(2)}`))
    }
  }

  // Rounding if exists
  if (bill.rounding && Number(bill.rounding) !== 0) {
    const roundingStr = `${Number(bill.rounding) > 0 ? '+' : ''}₹${Number(bill.rounding).toFixed(2)}`
    monoLines.push(padLine('Rounding', roundingStr))
  }

  monoLines.push(totalDivider)

  // TOTAL
  const totalStr = `₹${total.toFixed(2)}`
  monoLines.push(padLine('TOTAL', totalStr))
  monoLines.push(totalDivider)

  // Paid & Balance
  const paidStr = `₹${amountPaid.toFixed(2)}`
  const balanceStr = `₹${balance.toFixed(2)}`
  
  monoLines.push(padLine('Paid', paidStr))
  monoLines.push(padLine('Balance', balanceStr))

  const monoBlock = '```\n' + monoLines.join('\n') + '\n```'

  // Loyalty Points Earned Section
  let loyaltyText = ''
  if (settings.loyaltyEnabled !== false && bill.customerType === 'regular' && (bill.loyaltyPointsEarned > 0 || bill.customerTotalLoyaltyPoints > 0)) {
    const pointsEarned = bill.loyaltyPointsEarned || 0
    const pointsBalance = bill.customerTotalLoyaltyPoints || 0
    loyaltyText = `⭐ *Loyalty Points Added:* +${pointsEarned}\n⭐ *Loyalty Balance:* ${pointsBalance} pts\n`
  }

  const pdfUrlLine = pdfUrl ? `📥 *Download PDF Receipt:* ${pdfUrl}\n` : ''

  const footerText = 
    `🙏 Thank you for your business!\n\n` +
    `📍 Visit Again\n` +
    `📞 Contact us for support`

  const receiptBody = [
    header,
    divider,
    metadataSection,
    divider,
    monoBlock,
    divider,
    loyaltyText + pdfUrlLine + footerText,
    divider,
    `Generated by PrintPro POS`
  ].filter(Boolean).join('\n')

  return receiptBody
}
